### ISSUE TITLE
不能识别嵌套

### ISSUE THREAD

**Issue by windflowerly** [zerofang/myDBMS#1]
select语句的嵌套似乎不能解析。

**Comment by zerofang** [comment]
对，确实是不支持嵌套的SQL，支持的SQL比较简单，最复杂的也就只有多表查询，你可以看readme里面的支持的测试语句。



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： windflowerly <notifications@github.com>
日期: 2019/4/11 17:23 (GMT+08:00)
收件人： zerofang/myDBMS <myDBMS@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [zerofang/myDBMS] 不能识别嵌套 (#1)


select语句的嵌套似乎不能解析。

―

**Comment by windflowerly** [comment]
yacc 默认只能通过标准输入设备或文件解析SQL。
那怎么能够让yacc直接解析一个常量字符串呢？

**Comment by zerofang** [comment]
你可以试试在yacc编译出来的c程序里加函数
